server:
  port: 9999
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: root
  graalvm:
    build-time-properties:
      spring:
        native:
          remove-yaml-support: false
          remove-xml-support: false
          remove-spel-support: false
          remove-jmx-support: false
          remove-jdbc-support: false
          remove-naming-support: false
          remove-jaxb-support: false
          verbose: true
          mode: mode
        aop:
          proxyTargetClass: true